# Generated by Django 5.0.6 on 2024-05-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Сurrencies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.PositiveSmallIntegerField()),
                ("text_code", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=5, max_digits=10)),
                ("date", models.DateField()),
            ],
            options={
                "db_table": "currencies",
            },
        ),
    ]
