# Generated by Django 5.0.6 on 2024-05-16 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.PositiveSmallIntegerField()),
                ("text_code", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "currency",
            },
        ),
        migrations.CreateModel(
            name="HistoryCurrencies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=5, max_digits=10)),
                ("date", models.DateTimeField()),
                ("actualy_end", models.DateTimeField()),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "db_table": "history_currencies",
            },
        ),
    ]
